name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Checkout asdf project
      run: git clone https://github.com/asdf-vm/asdf.git

    - name: Test kubectl plugin
      run: |
        source asdf/asdf.sh
        asdf plugin-test kubectl https://github.com/${GITHUB_REPOSITORY}.git

